const backgrounds = {
    "Test Subject": ["Spell: Magic missile", "Lead coat (Heavy armour)"],
    "Kitchen Forager": ["Shield & jerkin (Light armour)", "Cookpots"],
    "Cage Dweller": ["Spell: Restore", "Holy symbol"],
    "Hedge Witch": ["Spell: Heal", "Incense stick"],
    "Leatherworker": ["Shield & jerkin (Light armour)", "Shears"],
    "Street Tough": ["Dagger (Light, d6)", "Flask of Coffee"],
    "Mendicant priest": ["Spell: Be understood", "Bottle of milk"],
    "Beetleherd": ["Hireling: Loyal beetle", "Pole, 6ft"],
    "Ale Brewer": ["Hireling: Drunken torchbearer", "Small barrel of ale"],
    "Fishermouse": ["Needle (Light, d6)", "Net"],
    "Blacksmith": ["Hammer (Medium, d6/d8)", "Metal File"],
    "Wireworker": ["Wire, spool", "Electric lantern"],
    "Woodcuttter": ["Axe (Medium, d6/d8)", "Twine, roll"],
    "Bat Cultist": ["Spell: Darkness", "Bag of bat teeth"],
    "Tin Miner": ["Pickaxe (Medium, d6/d8)", "Lantern"],
    "Trash Collector": ["Trashhook (Heavy, d10)", "Mirror"],
    "Wall Rover": ["Fishhook", "Thread, spool"],
    "Merchant": ["Hireling: Pack rat", "20p IOU from a noblemouse"],
    "Raft Crew": ["Hammer (Medium, d6/d8)", "Wooden Spikes"],
    "Worm Wrangler": ["Pole, 6ft", "Soap"],
    "Sparrow Rider": ["Fishhook", "Goggles"],
    "Sewer Guide": ["Metal File", "Thread, spool"],
    "Prison Guard": ["Chain, 6ft", "Spear (Heavy, d10)"],
    "Fungus Farmer": ["Dried mushroom (as rations)", "Spore Mask"],
    "Dam Builder": ["Shovel", "Wooden Spikes"],
    "Cartographer": ["Quill & Ink", "Compass"],
    "Trap Thief": ["Block of cheese", "Glue"],
    "Vagabond": ["Tent", "Treasure map, dubious"],
    "Grain Farmer": ["Spear (Heavy, d10)", "Whistle"],
    "Message Runner": ["Bedroll", "Documents, sealed"],
    "Troubadour": ["Musical Instrument", "Disguise kit"],
    "Gambler": ["Set of loaded dice", "Mirror"],
    "Sap Tapper": ["Bucket", "Wooden spikes"],
    "Bee Keeper": ["Jar of honey", "Net"],
    "Librarian": ["Scrap of obscure book", "Quill & Ink"],
    "Pauper Noblemouse": ["Felt Hat", "Perfume"]
}

